### ISSUE TITLE
8Plus图片显示的是三列，怎么解决这个问题呢？

### ISSUE THREAD

**Issue by ETmanwenhan** [Darren-chenchen/CLImagePickerTool#11]
8Plus图片显示的是三列，怎么解决这个问题呢？
![ff5b210b-328a-4125-90a1-7009e1f924f6](https://user-images.githubusercontent.com/5837888/35470972-bf1b8d18-038d-11e8-8c06-63c79854bc12.png)

**Comment by Darren-chenchen** [comment]
感谢反馈，我在优化一下

**Comment by Darren-chenchen** [comment]
已解决，版本2.2.3，ios11的问题
