### ISSUE TITLE
模拟器访问相机会出现崩溃哦

### ISSUE THREAD

**Issue by ETmanwenhan** [Darren-chenchen/CLImagePickerTool#12]
相机在外面就不会崩溃，相机在里面就会出现崩溃。好奇怪
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Source type 1 not available'

2   UIKit                               0x000000010a0693a6 -[UIImagePickerController sourceType] + 0

**Comment by Darren-chenchen** [comment]
好的，我处理一下

**Comment by Darren-chenchen** [comment]
版本2.2.4已处理
