### ISSUE TITLE
使用了单选和裁剪功能，但是拿到的图片并不是裁剪过的

### ISSUE THREAD

**Issue by a1259667899** [Darren-chenchen/CLImagePickerTool#14]
图片选择界面的裁剪框比例确实改变了，但是最终拿到的图片还是原图

**Comment by Darren-chenchen** [comment]
我看实例程序是好的，加个好友交流吧，我的qq  1597887620

**Comment by a1259667899** [comment]
是我弄错了，不好意思啊，我取了压缩之后的图片，那个是没有裁剪过的，setupImagePickerWith(MaxImagesCount: 1, superVC: self) { (PHAsset, image) in  
}这个方法拿到的图片是裁剪过的，SDK有没有提供拍照之后裁剪的功能？

**Comment by Darren-chenchen** [comment]
已解决
