### ISSUE TITLE
不能调用系统相册

### ISSUE THREAD

**Issue by Leoli0813** [Darren-chenchen/CLImagePickerTool#2]
只有用户相册

**Comment by Darren-chenchen** [comment]
智能14个
Optional("Favorites")相册,共有照片数:0
Optional("Recently Deleted")相册,共有照片数:0
Optional("Panoramas")相册,共有照片数:0
Optional("Camera Roll")相册,共有照片数:5
Optional("Slo-mo")相册,共有照片数:0
Optional("Screenshots")相册,共有照片数:0
Optional("Bursts")相册,共有照片数:0
Optional("Videos")相册,共有照片数:0
Optional("Selfies")相册,共有照片数:0
Optional("Hidden")相册,共有照片数:0
Optional("Time-lapse")相册,共有照片数:0
Optional("Recently Added")相册,共有照片数:0
Optional("Live Photos")相册,共有照片数:0
Optional("Depth Effect")相册,共有照片数:0
用户创建0个
一般来说这些相册就足够了，所有照片中含有全部照片

**Comment by Darren-chenchen** [comment]
已经修复
