### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by RayJiang16** [Darren-chenchen/CLImagePickerTool#22]
`private var  superVC: UIViewController?`
应该改成
`private weak var  superVC: UIViewController?`
否则调用方的控制器无法释放的

提一些建议

1.希望作者把`CLPickersTools.instence.clearPicture()`设为公有方法（虽然可以手动删UserDefaults），我想大部分的需求是选好图片之后，可以继续添加，之前加过的图片应该还是勾选状态，现在的状态是选好图片，继续添加的时候，之前勾选的图片都没了。

2.希望作者提供一个没有拍照的选项，就是当`cameraOut = false`样式的时候，选图片的最后不要带上拍照的item

3.希望作者提供一个`tineColor`属性，可以改变“预览”、“重设”按钮的颜色

最后感谢作者提供的库~

**Comment by Darren-chenchen** [comment]
非常感谢您的提醒，我尽快优化

**Comment by Darren-chenchen** [comment]
已修复（3.0.0），文档已更新
