### ISSUE TITLE
XS MAX 适配

### ISSUE THREAD

**Issue by JQShan1993** [Darren-chenchen/CLImagePickerTool#24]
XS MAX 适配Navigation和底部问题，内置拍照按钮不显示
![IMG_0328](https://user-images.githubusercontent.com/19809359/54270891-5b089200-45bb-11e9-89a1-2f30995c38c9.PNG)

**Comment by JQShan1993** [comment]
拍照按钮不显示，是因为系统语言

**Comment by Darren-chenchen** [comment]
> 拍照按钮不显示，是因为系统语言

能够把你的代码复制看一下，你说的因为系统语言，你是什么语言

**Comment by JQShan1993** [comment]
日文系统就没有，换成简体中文就显示了

**Comment by Darren-chenchen** [comment]
> 日文系统就没有，换成简体中文就显示了

是这样的，只有在全部照片中才会有这个拍照图片，在其他相册中没有
![图片](https://user-images.githubusercontent.com/16269032/54341975-40dfba00-4676-11e9-9c07-4091d016a816.png)

**Comment by Darren-chenchen** [comment]
已适配xs  3.0.2

**Comment by JQShan1993** [comment]
CLImageAmplifyView页面selectBtn没适配x以上，版本3.0.2,就是看到了说一下。

**Comment by Darren-chenchen** [comment]
> CLImageAmplifyView页面selectBtn没适配x以上，版本3.0.2,就是看到了说一下。

多谢，抽空我调整下
