### ISSUE TITLE
设置tineColor没有生效

### ISSUE THREAD

**Issue by libosama** [Darren-chenchen/CLImagePickerTool#25]
设置tineColor没有生效

**Comment by libosama** [comment]
imagePickTool.tineColor = UIColor.colorWithHexString(Main_Color)  我是这样设置的

**Comment by Darren-chenchen** [comment]
你发具体的使用方式发出来，看下我的事例程序是有改变的

**Comment by libosama** [comment]
您好 我是这么设置的 
let imagePickTool = CLImagePickerTool()
            imagePickTool.cameraOut = true
            imagePickTool.singleImageChooseType = .singlePicture
            imagePickTool.isHiddenVideo = true
            imagePickTool.tineColor = UIColor.red
            imagePickTool.cl_setupImagePickerWith(MaxImagesCount: 1) { (asset,cutImage) in
                print("返回的asset数组是\(asset)")
                let imageArr = CLImagePickerTool.convertAssetArrToThumbnailImage(assetArr: asset, targetSize: CGSize(width: 80, height: 80))
                print(imageArr)
            
            }

**Comment by libosama** [comment]
但是 在图片浏览器中的 确定 和 编辑按钮还是绿色的

**Comment by Darren-chenchen** [comment]
> 但是 在图片浏览器中的 确定 和 编辑按钮还是绿色的

已修复，最新版本3.0.3已发布

**Comment by libosama** [comment]
太感谢了  我试一下
