### ISSUE TITLE
点击头像初始化特别慢

### ISSUE THREAD

**Issue by libosama** [Darren-chenchen/CLImagePickerTool#26]
你好 现在遇到的问题是这样的  我在点击cell的时候 会初始化当前组件  但是要等一段时间才能弹出照片选择还是相机选择的alertView

**Comment by libosama** [comment]
这时我得用用法
if indexPath.row == 0{
            MHLog("选择头像")
            let imagePickTool = CLImagePickerTool()
            imagePickTool.cameraOut = true
            imagePickTool.singleImageChooseType = .singlePicture
            imagePickTool.isHiddenVideo = true
            imagePickTool.tineColor = UIColor.colorWithHexString(Main_Color)
            imagePickTool.cl_setupImagePickerWith(MaxImagesCount: 1) { (asset,cutImage) in
                print("返回的asset数组是\(asset)")
                let imageArr = CLImagePickerTool.convertAssetArrToThumbnailImage(assetArr: asset, targetSize: CGSize(width: 80, height: 80))
                print(imageArr)
            }
        }

**Comment by Darren-chenchen** [comment]
你把CLImagepicker设置成全局的试一下，你放在 cell中不是会创建很多次吗

**Comment by libosama** [comment]
我是在点击cell的时候才创建的  确实只是创建了一次

**Comment by libosama** [comment]
你好 问题已经解决 需要在func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)中加入tableView.deselectRow(at: indexPath, animated: false)
