### ISSUE TITLE
PopViewUtil 的使用问题

### ISSUE THREAD

**Issue by libosama** [Darren-chenchen/CLImagePickerTool#27]
PopViewUtil.share.stopLoading()  使用后会报 share  is inaccessible due to 'internal' protection level  权限的问题 我在方法前加上了public就可以正常使用了

**Comment by Darren-chenchen** [comment]
我最初是没有打算开放PopViewUtils的，我晚上把这块开发出来吧

**Comment by Darren-chenchen** [comment]
> PopViewUtil.share.stopLoading() 使用后会报 share is inaccessible due to 'internal' protection level 权限的问题 我在方法前加上了public就可以正常使用了

已更新3.0.4
