### ISSUE TITLE
在cl_setupImagePickerWith回调里，UIView.animate无效果

### ISSUE THREAD

**Issue by Jason318** [Darren-chenchen/CLImagePickerTool#28]
我有个动画效果，需要再选完图片后动态排放图片，但在这个回调函数里动画没有起到效果，我还是在DispatchQueue.main.async主线程里调用的动画

**Comment by Darren-chenchen** [comment]
请你粘贴一下代码

**Comment by Jason318** [comment]
@objc func addImages() {

        let imagePickTool = CLImagePickerTool()
        imagePickTool.isHiddenVideo = true
        imagePickTool.cl_setupImagePickerWith(MaxImagesCount: 10, superVC: obtainCurrentVC()) {[weak self] (asset, cutImage) in
            print("返回的asset数组是\(asset)")
            guard let strongSelf = self else {
                return
            }
//            /// 获取缩略图，耗时较短
//            let imageArr = CLImagePickerTool.convertAssetArrToThumbnailImage(assetArr: asset, targetSize: CGSize(width: 80, height: 80))
//            print(imageArr)

              strongSelf.showImages()
        }
    }

func showImages() {

        let totalRow = ceil(Double((photosArray.count))/3.0)
        let height = (imageWAH + CGFloat(imageSpace)) * CGFloat(totalRow)
        imagesScrollView.contentSize = CGSize(width: kSCREENWIDTH - 15.0, height: height)
        if choosedImagesCompletion != nil {
            choosedImagesCompletion!(Float(height))
        }

        /// 删除图片btn
        for subview in imagesScrollView.subviews {
            let btnTag = subview.tag
            if subview.isKind(of: UIButton.classForCoder()) && btnTag >= kIMAGEBASETAG && btnTag < kIMAGEBASETAG + 9 {
                subview.removeFromSuperview()
            }
        }

        /// 删除“删除”btn
        for subview in imagesScrollView.subviews {
            let btnTag = subview.tag
            if subview.isKind(of: UIButton.classForCoder()) && btnTag >= kDELETEBTNBASETAG && btnTag < kDELETEBTNBASETAG + 9 {
                subview.removeFromSuperview()
            }
        }

        for index in 0..<photosArray.count {
            let image = photosArray[index]

            let imageBtn = UIButton(type: .roundedRect)
            imageBtn.isAddButton = image.isAddButton

            /// 行
            let row = ceil(Double((index + 1))/3.0)

            /// 列
            let column = (index % 3)

            /// 目标位置
            let targetOrigin = CGPoint(x: CGFloat(column) * (imageWAH + CGFloat(imageSpace)), y: CGFloat(imageSpace) + CGFloat((row - 1)) * (imageWAH + CGFloat(imageSpace)))

            imageBtn.frame = CGRect(x: 0.0, y: CGFloat(imageSpace), width: imageWAH, height: imageWAH)
            imageBtn.setImage(image.withRenderingMode(.alwaysOriginal), for: .normal)
            imageBtn.imageView?.contentMode = .scaleAspectFill
            imageBtn.tag = kIMAGEBASETAG + index
            imageBtn.addTarget(self, action: #selector(imageBtnClick(button:)), for: .touchUpInside)
            imagesScrollView.addSubview(imageBtn)

            UIView.animate(withDuration: 2, delay: 0, options: UIView.AnimationOptions.curveLinear, animations: {
              imageBtn.frame = CGRect(x: targetOrigin.x, y: targetOrigin.y, width: self.imageWAH, height: self.imageWAH)

               self.imagesScrollView.layoutIfNeeded()
          }) { (completion) in
               imageBtn.frame = CGRect(x: targetOrigin.x, y: targetOrigin.y, width: self.imageWAH, height: self.imageWAH)
          }
        }
    }

**Comment by Jason318** [comment]
addImages()方法在其他地方调用是有动画效果的，在cl_setupImagePickerWith的block里调用看不到效果，动画直接跳到了结果

**Comment by Darren-chenchen** [comment]
建议你延迟0.1秒试下   DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1, execute: {
                self.photoScrollView2.picArr = imageArr
            })

**Comment by Jason318** [comment]
确实可以，这是和你异步获取图片的线程有冲突吗

**Comment by Darren-chenchen** [comment]
是因为我内部的处理有点小问题，再dismiss之前我就触发回调函数，现在我改过来了。谢谢你！，我更新一下，延迟0.1s也可以。
weakSelf?.dismiss(animated: true) {
            weakSelf?.navigationController?.popViewController(animated: true)
            
            if weakSelf?.singleChooseImageCompleteClouse != nil {
                weakSelf?.singleChooseImageCompleteClouse!(assetArr,img)
            } 
        }
