### ISSUE TITLE
真机下 界面只能显示用户创建的图片

### ISSUE THREAD

**Issue by ITLiuFei** [Darren-chenchen/CLImagePickerTool#3]
真机下 界面只能显示用户创建的图片

**Comment by Darren-chenchen** [comment]
在我的设备上可以访问到相册中的所有照片，我的10.3的系统，请问你的系统是什么？

**Comment by ITLiuFei** [comment]
我把系统语言切换成英语就好了 
还有 fetchAllSystemAblum函数var titleStr: String? 到最后 替换成 dataArr.append([assetCollection.localizedTitle!:array])
也可以了

**Comment by Darren-chenchen** [comment]
已修复，非常感谢！

**Comment by JSvane** [comment]
目前发现两个问题：
1. 看了代码，self.collectionView?.scrollToItem(at: lastItemIndex, at: .top, animated: false)方法好像没有被调用，因此collectionView是没有滚动到底部的，也就是指本地照片/视频是历史最早的，很不方便用户选择最新的照片/视频；
2.优化问题：当照片/视频数量足够多时，快速滚动到顶部/底部，会出现图片加载跟不上的情况，不过不影响使用，希望作者有时间可以优化一下；

**Comment by Darren-chenchen** [comment]
1.你那边没有滚动到最底部的，我这边是可以的，进去就是展示在最底部
