### ISSUE TITLE
拍照返回两个图片数据。

### ISSUE THREAD

**Issue by chaolianjun** [Darren-chenchen/CLImagePickerTool#39]
ios13，拍照返回两个图片数据。 

修改 CLPickersTools.swift  获取原图方法。      option.isSynchronous = true
数据正常了， 

    //5、获取原图的方法
    func getAssetOrigin(asset:PHAsset,dealImageSuccess:@escaping (UIImage?,[AnyHashable:Any]?) -> ()) -> Void {
        
        //获取原图
        let manager = PHImageManager.default()
        let option = PHImageRequestOptions() //可以设置图像的质量、版本、也会有参数控制图像的裁剪
            option.isSynchronous = true
        manager.requestImage(for: asset, targetSize:PHImageManagerMaximumSize, contentMode: .aspectFit, options: option) { (originImage, info) in
            dealImageSuccess(originImage,info)
        }
    }

**Comment by Darren-chenchen** [comment]
感谢反馈已修复3.1.0
