### ISSUE TITLE
在 iOS 13.1.3 下，拍照保存到本地相册成功后，在进入裁剪功能的时候，裁剪页面展示的图片跟刚刚拍的不一致。用这个库的相册也看不到刚刚拍的照片，但在系统相册是看得到的。

### ISSUE THREAD

**Issue by zhangxiaowei0312** [Darren-chenchen/CLImagePickerTool#40]

**Comment by Darren-chenchen** [comment]
感谢反馈，我试了， 但是没有发现这个问题，如果有可能的话，麻烦你再调试一下，找到问题的原因，我这边可以合并下，谢谢

**Comment by zhangxiaowei0312** [comment]
> 感谢反馈，我试了，但是没有发现这个问题，如果有可能的话，麻烦你再调试一下，发现问题的原因，我这边可以合并下，谢谢

这样的话，那应该就不是iOS13的问题了，那就有可能是港版跟大陆版的问题了。我手机是港版的，我拿了大陆版的对比了一下。发现相册的名称有一个坑。大陆版的“Camera Roll”，在港版叫做“Recents”。所以我港版这边找不到“Camera Roll”，就默认第一个相册“Screenshots”了。。。所以出现了我提的这个issue。。。
这里应该添加一个“Recents”
<img width="271" alt="屏幕快照 2019-10-22 下午2 59 31" src="https://user-images.githubusercontent.com/55971976/67265906-7472a480-f4e1-11e9-9f6b-eba6123fe8ad.png">


这是港版

<img width="426" alt="屏幕快照 2019-10-22 下午2 59 57" src="https://user-images.githubusercontent.com/55971976/67266061-db905900-f4e1-11e9-9c52-2db7f7d02a31.png">



这是大陆版
<img width="339" alt="屏幕快照 2019-10-22 下午3 14 41" src="https://user-images.githubusercontent.com/55971976/67265720-0332f180-f4e1-11e9-954e-273cdc337eb1.png">

**Comment by zhangxiaowei0312** [comment]
> > 感谢反馈，我试了，但是没有发现这个问题，如果有可能的话，麻烦你再调试一下，发现问题的原因，我这边可以合并下，谢谢
> 
> 这样的话，那应该就不是iOS13的问题了，那就有可能是港版跟大陆版的问题了。我手机是港版的，我拿了大陆版的对比了一下。发现相册的名称有一个坑。大陆版的“Camera Roll”，在港版叫做“Recents”。所以我港版这边找不到“Camera Roll”，就默认第一个相册“Screenshots”了。。。所以出现了我提的这个issue。。。
> 这里应该添加一个“Recents”
> <img alt="屏幕快照 2019-10-22 下午2 59 31" width="271" src="https://user-images.githubusercontent.com/55971976/67265906-7472a480-f4e1-11e9-9f6b-eba6123fe8ad.png">
> 
> 这是港版
> 
> <img alt="屏幕快照 2019-10-22 下午2 59 57" width="426" src="https://user-images.githubusercontent.com/55971976/67266061-db905900-f4e1-11e9-9c52-2db7f7d02a31.png">
> 
> 这是大陆版
> <img alt="屏幕快照 2019-10-22 下午3 14 41" width="339" src="https://user-images.githubusercontent.com/55971976/67265720-0332f180-f4e1-11e9-954e-273cdc337eb1.png">
港版找不到“Recents”，从代码来看，就默认进入 “截图”那个相册了。。。

**Comment by zhangxiaowei0312** [comment]
> > > 感谢反馈，我试了，但是没有发现这个问题，如果有可能的话，麻烦你再调试一下，发现问题的原因，我这边可以合并下，谢谢
> > 
> > 
> > 这样的话，那应该就不是iOS13的问题了，那就有可能是港版跟大陆版的问题了。我手机是港版的，我拿了大陆版的对比了一下。发现相册的名称有一个坑。大陆版的“Camera Roll”，在港版叫做“Recents”。所以我港版这边找不到“Camera Roll”，就默认第一个相册“Screenshots”了。。。所以出现了我提的这个issue。。。
> > 这里应该添加一个“Recents”
> > <img alt="屏幕快照 2019-10-22 下午2 59 31" width="271" src="https://user-images.githubusercontent.com/55971976/67265906-7472a480-f4e1-11e9-9f6b-eba6123fe8ad.png">
> > 这是港版
> > <img alt="屏幕快照 2019-10-22 下午2 59 57" width="426" src="https://user-images.githubusercontent.com/55971976/67266061-db905900-f4e1-11e9-9c52-2db7f7d02a31.png">
> > 这是大陆版
> > <img alt="屏幕快照 2019-10-22 下午3 14 41" width="339" src="https://user-images.githubusercontent.com/55971976/67265720-0332f180-f4e1-11e9-954e-273cdc337eb1.png">
> > 港版找不到“Recents”，从代码来看，就默认进入 “截图”那个相册了。。。

打错，港版找不到“Cameron Roll”
