### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by JSvane** [Darren-chenchen/CLImagePickerTool#5]
1.看了代码，self.collectionView?.scrollToItem(at: lastItemIndex, at: .top, animated: false)方法好像没有被调用，因此collectionView是没有滚动到底部的，也就是指本地照片/视频是历史最早的，很不方便用户选择最新的照片/视频；
2.优化问题：当照片/视频数量足够多时，快速滚动到顶部/底部，会出现图片加载跟不上的情况，不过不影响使用，希望作者有时间可以优化一下；

**Comment by Darren-chenchen** [comment]
已优化
