### ISSUE TITLE
拍照过后，代理方法不走！

### ISSUE THREAD

**Issue by cccey** [Darren-chenchen/CLImagePickerTool#9]
如题！拍照过后没有反应

**Comment by Darren-chenchen** [comment]
谢谢你的反馈，我已经修复swift4.0 拍照的问题，请使用最新版2.1.8，尝试下是否解决你的问题

**Comment by cccey** [comment]
@Darren-chenchen 不添加一个方法获取回调拍摄的照片么？？？CLImagePickerTool  280行这个获取拍摄照片代理不走！最新版也是一样

**Comment by Darren-chenchen** [comment]
不好意思，我遗漏了一点，这个地方需要将CLImagePickersTool设置成全局变量，因为局部变量的话，{}完成就销毁了，自然不走代理，
// 如果是单独访问相机，一定要声明为全局变量
    let imagePickTool = CLImagePickersTool()

    // 相机在外部
    @IBAction func clickBtn2(_ sender: Any) {
        
        imagePickTool.cameraOut = true
        
        imagePickTool.setupImagePickerWith(MaxImagesCount: 6, superVC: self) { (asset,cutImage) in
            print("返回的asset数组是\(asset)")
        }
        
    }

**Comment by Darren-chenchen** [comment]
加我qq。比较及时  1597887620

**Comment by cccey** [comment]
@Darren-chenchen 我才开始学习swift，感觉都写懵逼了😳！QQ早都不用了！有问题我就提issues了！
